# Generated by Django 4.2.7 on 2023-12-07 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myEmployeeList', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
