# Generated by Django 4.2.7 on 2023-12-08 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myEmployeeList', '0004_alter_teammember_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='admin'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='is_regular',
            field=models.BooleanField(default=True, verbose_name='regular'),
        ),
    ]
