# Generated by Django 4.2.7 on 2023-12-08 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myEmployeeList', '0005_teammember_is_admin_teammember_is_regular'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='client_approved',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('cancelled', 'Cancelled')], default='yes', max_length=25),
        ),
    ]
