# Generated by Django 4.2.7 on 2023-12-08 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myEmployeeList', '0006_teammember_client_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='client_approved',
        ),
        migrations.AddField(
            model_name='teammember',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
    ]
