# Generated by Django 4.2.7 on 2023-12-08 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myEmployeeList', '0007_remove_teammember_client_approved_teammember_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='gender',
        ),
    ]
