# Generated by Django 4.2.7 on 2023-12-08 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myEmployeeList', '0008_remove_teammember_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='is_regular',
        ),
        migrations.AddField(
            model_name='teammember',
            name='user_type',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher')], default='student', max_length=10),
        ),
    ]
