# Generated by Django 4.2.7 on 2023-12-08 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myEmployeeList', '0009_remove_teammember_is_admin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='user_type',
        ),
    ]
