# Generated by Django 4.2.7 on 2023-12-08 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myEmployeeList', '0010_remove_teammember_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='test',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher')], default='student', max_length=10),
        ),
    ]
