# Generated by Django 4.2.7 on 2023-12-08 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myEmployeeList', '0015_remove_teammember_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teammember',
            old_name='is_student',
            new_name='admin',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='is_teacher',
        ),
        migrations.AddField(
            model_name='teammember',
            name='regular',
            field=models.BooleanField(default=True),
        ),
    ]
