# Generated by Django 4.2.7 on 2023-12-08 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myEmployeeList', '0016_rename_is_student_teammember_admin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='regular',
        ),
    ]
