# Generated by Django 4.2.7 on 2023-12-08 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myEmployeeList', '0017_remove_teammember_admin_remove_teammember_regular'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='member_type',
            field=models.CharField(choices=[('regular', 'Regular'), ('admin', 'Admin')], default='regular', max_length=10),
        ),
    ]
