# Generated by Django 4.2.7 on 2023-12-08 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myEmployeeList', '0018_teammember_member_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='member_type',
            field=models.CharField(choices=[('regular', 'Regular'), ('admin', 'Admin')], max_length=10),
        ),
    ]
